giginet/Scipio

- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
Refactor FrameworkProducer referred in #15
@mtj0928 Please review
> Improve readability of Compiler and FrameworkProducer

- Sources/ScipioKit/ProjectGenerator/BuildSettingsGenerator.swift
tvOS support was broken.
This PR fixes it.
> Fix tvOS platform settings

- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/ProjectGenerator/BuildSettingsGenerator.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/CreateCommands.swift
- Sources/scipio/Options.swift
- Sources/scipio/PrepareCommands.swift
- Tests/ScipioKitTests/RunnerTests.swift
closes #33
https://github.com/giginet/Scipio/pull/33/
I introduced new options `force`, `platforms`, `skip-project-generation`.
Creating XCFrameworks by `create` mode. Scipio aims to create for all supported platforms. So I added platform option.
> Add some cli options

- Sources/ScipioKit/ProjectGenerator/BuildFlagsGenerator.swift
- Sources/ScipioKit/ProjectGenerator/BuildSettingsGenerator.swift
- Sources/ScipioKit/ProjectGenerator/ProjectGenerator.swift
- Sources/ScipioKit/ProjectGenerator/XCConfigValue.swift
- Tests/ScipioKitTests/ProjectGeneratorTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/SettingsPackage/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/SettingsPackage/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/SettingsPackage/README.md
- Tests/ScipioKitTests/Resources/Fixtures/SettingsPackage/Sources/SettingsPackage/SettingsPackage.swift
closes #27 
I'm a git beginner, so I broke #33.
I re-submit this.
> Support build setting on manifests

- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/Producer/PIF/BuildParametersGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Sources/ScipioKit/Runner.swift
- Tests/ScipioKitTests/BuildOptionsTests.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
closes #25
Added a feature to pass extra build parameters and flags.
> Add extra build parameters and flags

- Package.swift
- README.md
- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/CommandType.swift
- Sources/scipio/Options.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
This PR should be review after merging https://github.com/giginet/Scipio/pull/47
This PR added `--disable-library-evolution` flag to disable Library Evolution.
Please read README
> Add option to specify enableLibraryEvolution

- .swiftlint.yml
- Package.resolved
- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/PrepareCommands.swift
- Tests/ScipioKitTests/RunnerTests.swift
I added some features to support remote caches.
- Modify accessibility of CacheKeys
- Modify `CacheStorage` protocol
- Add cache actor indicates uploading/downloading caches or not.
> Small update for cache storage

- README.md
"In default" in the README should be correctly expressed as "by default".
> Polishing English expression

- Sources/ScipioKit/Logger.swift
- Sources/ScipioKit/Producer/PIF/ModuleMapGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
I updated some linker settings to avoid some build issues.
- Fix using custom modulemap
- Added `link framework` declare on modulemap for convenience.
- Add dependencies in "Link Binary with Libraries" phase
> Update linker settings to support Clang frameworks

- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
Add hashes to logs for investigation
> Print cacheKey hash to logs

- Sources/ScipioKit/Executor.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
#83 と同じ内容をmainブランチ向けに作りました。
CIが通るはずです。
> [main] verboseモードの場合にはxcbuildの出力を表示する

- Sources/ScipioKit/Producer/PIF/ModuleMapGenerator.swift
- Tests/.swiftlint.yml
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithUmbrellaDirectory/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithUmbrellaDirectory/Sources/MyTarget/add.c
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithUmbrellaDirectory/Sources/MyTarget/include/add.h
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithUmbrellaDirectory/Sources/MyTarget/include/my_target.h
- Tests/ScipioKitTests/RunnerTests.swift
If the moduleMap types are detected as `umbrellaDirectory`, `publicHeaderPath` would be embedded into modulemaps distributed in frameworks.
Generated module map from the package with `umbrellaDirectory` type has an `umbrella` declare
```
framework module MyTarget {
umbrella "include"
export *
}
```
However, when headers are copied to frameworks, directory structures are lost.
So it would not work well.
This PR makes to change a generating modulemaps.
It expands directory contents recursively.
```
framework module MyTarget {
header "a.h"
header "b.h"
export *
}
```
> Fix moduleMap generation for umbrellaDirectory

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- Tests/ScipioKitTests/RunnerTests.swift
Support Xcode 15.3 to run tests on GitHub Action
> Support Xcode 15.3 on GitHub Action

- .github/workflows/release.yml
- Package.swift
Add action to upload artifact bundle
> Add workflow to upload Artifact Bundle

- Package.swift
- Package@swift-5.10.swift
- Package@swift-5.9.swift
SwiftPM is moved to `swiftlang` orgs
> Use swiftlang instead

- Sources/scipio/scipio.docc/build-pipeline.md
- Sources/scipio/scipio.docc/using-s3-storage.md
- https://github.com/giginet/Scipio/commit/b6b1c6a79f16fb69fa03bfb209a92f80abf2ba21
- https://github.com/giginet/scipio-s3-storage/releases/tag/2.0.0
- > Improve data structure of storage configuration
> Update documentation to follow changes in CacheMode and scipio-s3-storage v2

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/PackageLocator.swift
- Sources/ScipioKit/Producer/PIF/FrameworkComponentsCollector.swift
- Sources/ScipioKit/Runner.swift
- Sources/ScipioKit/SwiftPM+Compatibility.swift
- https://github.com/swiftlang/swift-package-manager/blob/bc689418acad746af6f2e24e6bef640e411d9bd7/Sources/Basics/FileSystem/AbsolutePath.swift#L16-L17
- https://github.com/swiftlang/swift-package-manager/blob/bc689418acad746af6f2e24e6bef640e411d9bd7/Sources/Basics/FileSystem/AbsolutePath.swift#L45-L48
> Remove ScipioAbsolutePath and use TSCAbsolutePath typealias instead

- .swiftlint.yml
- Sources/ScipioKit/Producer/PIF/FrameworkBundleAssembler.swift
- Sources/ScipioKit/Producer/PIF/FrameworkComponentsCollector.swift
- Tests/ScipioKitTests/FrameworkBundleAssemblerTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/ResourcePackage/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/ResourcePackage/Sources/ResourcePackage/Resources/PrivacyInfo.xcprivacy
- Tests/ScipioKitTests/RunnerTests.swift
> Move PrivacyInfo.xcprivacy from the resource bundle to the expected location inside the framework

- .github/workflows/release.yml
- Package.swift
This PR replace ArtifactBundleGen to github-action-artifactbundle.
https://github.com/giginet/github-action-artifactbundle
> Introduce github-action-artifactbundle

- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
> Surpress logging of stripping debug information

- Package.swift
- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
> Restore back SwiftPM `release/6.0` branch support

- .swiftlint.yml
- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Executor.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Sources/ScipioKit/Producer/PIF/XCBuildExecutor.swift
- Sources/ScipioKit/Resolver/PackageResolver.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/ProcessExecutorTests.swift
- Tests/ScipioKitTests/TestingExecutor.swift
Replace TSCBasic.ProcessExecutor to Foundation.Process
> Remove TSCBasic.ProcessExecutor
