- README.md
- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/ProjectGenerator.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/Arguments.swift
- Sources/scipio/CreateCommands.swift
- Sources/scipio/Options.swift
- Sources/scipio/PrepareCommands.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/PrepareTests.swift
- Tests/ScipioKitTests/XCConfigEncoderTests.swift
Add `--static` flag to generate Static Frameworks.
```
$ scipio prepare MyDependencies --static
$ file XCFrameworks/MyFramework.xcframework/ios-arm64/MyFramework.framework/MyFramework
XCFrameworks/MyFramework.xcframework/ios-arm64/MyFramework.framework/MyFramework: current ar archive
```
> Support Static Framework

- Sources/ScipioKit/Compiler.swift
The SDK name for macOS is not correct.
As a result, scipio cannot make xcframewrok for macOS.
I fixed the SDK name in this PR.
> Fix SDK name for macOS

- Sources/ScipioKit/Cache/CacheSystem.swift
- Sources/ScipioKit/Cache/LocalCacheStorage.swift
- Sources/ScipioKit/Compiler.swift
- Sources/ScipioKit/DebugSymbol.swift
- Sources/ScipioKit/Executor.swift
- Sources/ScipioKit/FileSystem.swift
- Sources/ScipioKit/Package.swift
- Sources/ScipioKit/ProjectGenerator.swift
- Sources/ScipioKit/Resolver.swift
- Sources/ScipioKit/Runner.swift
- Sources/ScipioKit/XcodeBuild/Commands/ArchiveCommand.swift
- Sources/ScipioKit/XcodeBuild/Commands/CleanCommand.swift
- Sources/ScipioKit/XcodeBuild/Commands/CreateXCFrameworkCommand.swift
- Sources/ScipioKit/XcodeBuild/XcodeBuildClient.swift
- Sources/ScipioKit/XcodeBuild/XcodeBuildCommand.swift
- Tests/ScipioKitTests/DebugSymbolTests.swift
- Tests/ScipioKitTests/PackageTests.swift
- Tests/ScipioKitTests/PrepareTests.swift
- Tests/ScipioKitTests/TestingExecutor.swift
related #3 
To remove SwiftPM dependencies, I'm going to drop swift-support-tools-core dependencies.
- Replace `TSCBasic.FileSystem` to original `FileSystem`
- Replace `TSCBasic.AbsolutePath` to `Foundation.URL`
Some implementations still use `TSCBasic`. they will be removed.
> Remove swift-support-tools-core

- Package.swift
We no longer only need `SwiftPMDataModel`. So I update the dependencies.
`SwiftPMDataModel-auto` is a static linking version of the product.
https://github.com/apple/swift-package-manager/blob/main/Package.swift#L53
> Use only SwiftPM DataModel

- Sources/ScipioKit/ProjectGenerator/BuildSettingsGenerator.swift
In some situations, `DEFINES_MODULE` is needed to build.
According to the swift-package-manager, Enable `DEFINES_MODULE` for all targets.
So I enable this for all targets.
> Enable DEFINES_MODULE for all targets

- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/Package.swift
- Sources/ScipioKit/Producer/Cleaner.swift
- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Runner.swift
- Tests/ScipioKitTests/Resources/Fixtures/E2ETestPackage/Package.swift
- Tests/ScipioKitTests/RunnerTests.swift
closes #12
I added `platformMatrix` to Runner.
```swift
let runner = Runner(
mode: .prepareDependencies,
options: .init(
buildConfiguration: .release,
isSimulatorSupported: true,
isDebugSymbolsEmbedded: false,
frameworkType: .dynamic,
cacheMode: .project,
platformMatrix: ["TargetName": [.iOS, .watchOS]],
verbose: false)
)
```
Passing this parameter, configure target platforms by each target.
> Introduce PlatformMatrix

- Sources/ScipioKit/Runner.swift
When in verbose mode, log output recommending verbose mode is no longer emitted.
> Improved messages in verbose mode

- Package.swift
- README.md
Use `.product(...)` instead of `.productItem(...)` in Package.swift and README.md.
SwiftPM adds `Target.Dependency` to the `dependencies` property as an object representing dependencies.
Dependency is an enum like the following. ([ref](https://github.com/apple/swift-package-manager/blob/release/5.7/Sources/PackageDescription/Target.swift#L42-L66))
```swift
/// The different types of a target's dependency on another entity.
public enum Dependency {
/// A denpendency on a target.
///
///  - Parameters:
///    - name: The name of the target.
///    - condition: A condition that limits the application of the target dependency. For example, only apply a dependency for a specific platform.
case targetItem(name: String, condition: TargetDependencyCondition?)
/// A dependency on a product.
/// …
```
> Use `.product(...)` instead of `.productItem(...)`

- Package.resolved
- Package.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
Currently, we use a fork. However, a required PR seems not to be accepted.
Use a public interface instead to avoid using forks.
> Use upstream SwiftPM

- Sources/ScipioKit/Executor.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
The output of `xcbuild` is hard to read. I introduce `ErrorDecorder` to format executor errors.
> Introduce ErrorDecoder

- Sources/scipio/CommandType.swift
- Tests/ScipioKitTests/RunnerTests.swift
Due to latest changes, `cacheMode` will be always disabled
> Fix cacheMode always become disabled on CLI

- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/CreateCommands.swift
The `sdk` of `BuildOptions` is `OrderedSet`, but some codes handles `sdk` as `Set<SDK>`.
As a result, the cache is sometimes not reused.
To fix the issue, I did
- Replacing most of `OrderedSet` with `Set`.
- Sorting the `sdk` when `BuildOptions` is created.
close #55
> Fix order issue of `BuildOptions` #55

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/PackageGraph+Extensions.swift
- Sources/ScipioKit/Producer/PIF/ModuleMapGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithCustomModuleMap/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithCustomModuleMap/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithCustomModuleMap/README.md
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithCustomModuleMap/Sources/ClangPackageWithCustomModuleMap/include/module.modulemap
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithCustomModuleMap/Sources/ClangPackageWithCustomModuleMap/include/mycalc.h
- Tests/ScipioKitTests/Resources/Fixtures/ClangPackageWithCustomModuleMap/Sources/ClangPackageWithCustomModuleMap/src/mycalc.c
- Tests/ScipioKitTests/RunnerTests.swift
xcbuild also generates modulemaps. However, these are not for including final frameworks.
Therefore, Scipio generates modulemaps for frameworks manually.
If custom modulemap is included, convert them for frameworks.
> Implement ModuleMapGenerator

- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
These link settings are already added on SwiftPM's `PIFBuilder`.
So this process causes duplicated symbols when libraries are statics.
I checked in some situations this change will work fine.
> Remove addLink process to avoid duplicated symbols

- Sources/ScipioKit/Producer/InfoPlistGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
Auto-generated Info.plist causes code signing issue when submitting to AppStore.
Generate Info.plist for resource bundle.
> Generate Info.plist for resource bundles

- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/scipio/DumpCacheKey.swift
- Sources/scipio/Scipio.swift
Add subcommand `dump-cache-key` to dump VersionFile
```
$ scipio dump-cache-key XCFrameworks/.Logging.version
```
> Add subcommand to dump cache key

- .github/workflows/ci.yml
- Package.resolved
- Sources/ScipioKit/DescriptionPackage.swift
I enabled flag `--disable-automatic-resolution` when package dependencies are resolved.
This flag enables the resolver doesn't change `Package.resolved`.
> Enable --disable-automatic-resoltion when resolves package

- .gitignore
- Sources/ScipioKit/DescriptionPackage.swift
- Tests/ScipioKitTests/Resources/Fixtures/E2ETestPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationTestPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/TestingPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/UsingBinaryPackage/Package.resolved
I was mistaken.
`forceResolvedVersions` should be `true`. Default value is `false`
https://github.com/apple/swift-package-manager/blob/main/Sources/CoreCommands/Options.swift
> Invert forceResolvedVersions

- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/Runner.swift
In this PR, I added support for visionOS to scipio.
I confirmed that the generated XFramework for the below package can be used on visionOS project.
```swift
// swift-tools-version: 5.9
import PackageDescription
let package = Package(
name: "Dependencies",
platforms: [.visionOS(.v1)],
products: [
.library(name: "Dependencies", targets: ["Dependencies"]),
],
dependencies: [
.package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMajor(from: "5.6.4"))
],
targets: [
.target(name: "Dependencies", dependencies: ["Alamofire"]),
.testTarget(name: "DependenciesTests", dependencies: ["Dependencies"]),
]
)
```
And, I noticed that `destination` of `SDK` is not used, so I removed the propertiy.
> Support visionOS

- Tests/ScipioKitTests/DescriptionPackageTests.swift
- Tests/ScipioKitTests/IntegrationTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationMacTestPackage/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationMacTestPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationMacTestPackage/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationMacTestPackage/Sources/IntegrationMacTestPackage/Dummy.swift
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationTestPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationTestPackage/Package.swift
#87 #88 によって、 swift-nio-sslがビルドできるようになったので、
それをテストで保守します。
これがマージされたら #80 をクローズしたいです。
> NIOSSLのテストを追加する

- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Tests/ScipioKitTests/IntegrationTests.swift
- fix: https://github.com/giginet/Scipio/issues/101
correctly copy `dSYMs` directory into xcframeworks.
testsed with Xcode 14.3.1
```
$ /Users/hyde/gitclone/Scipio/.build/arm64-apple-macosx/release/scipio prepare --embed-debug-symbols --support-simulators
🔁 Resolving Dependencies...
📦 Building Alamofire for iOS, iPhone Simulator
🚀 Combining into XCFramework...
🚀 Cache Alamofire.xcframework to cache storage
❇️ Succeeded.
$ tree XCFrameworks
XCFrameworks
└── Alamofire.xcframework
├── Info.plist
├── ios-arm64
│   ├── Alamofire.framework
│   │   ├── Alamofire
│   │   ├── Headers
│   │   │   └── Alamofire-Swift.h
│   │   ├── Info.plist
│   │   └── Modules
│   │       ├── Alamofire.swiftmodule
│   │       │   ├── Project
│   │       │   │   └── arm64-apple-ios.swiftsourceinfo
│   │       │   …
```
> fix: `--embed-debug-symbols` option is not working

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/CommandType.swift
- Sources/scipio/Options.swift
- Sources/scipio/scipio.docc/prepare-cache-for-applications.md
- Tests/ScipioKitTests/DescriptionPackageTests.swift
- Tests/ScipioKitTests/IntegrationTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
closes #97
Introduce new option `--only-use-versions-from-resolved-file`.
Enabling this option, SwiftPM never updated `Package.resolved` automatically.
If `Package. resolved` and the existing workspace is mismatched, resolving will fail.
Since this PR, the default behavior is changed. The default value becomes `false`.
Because it's inconvenient to enable this for common use cases.
> Add option to enable manifest update closes #97

- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Tests/ScipioKitTests/RunnerTests.swift
Since 0.17.0, these values are missing in Info.plist
It causes validation error on AppStore.
> Add CFBundleVersion and CFBundleShortVersionString to Info.plist

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- .swiftlint.yml
- Package@swift-5.9.swift
- README.md
- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Producer/BinaryExtractor.swift
- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/InfoPlistGenerator.swift
- Sources/ScipioKit/Producer/PIF/BuildParametersGenerator.swift
- Sources/ScipioKit/Producer/PIF/FrameworkComponentsCollector.swift
- Sources/ScipioKit/Producer/PIF/ModuleMapGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/ToolchainGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildExecutor.swift
- Sources/ScipioKit/Runner.swift
- Sources/ScipioKit/SwiftPM+Compatibility.swift
- Sources/ScipioKit/TSCBasics+Extensions.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationTestPackage/Package.resolved
- Tests/ScipioKitTests/RunnerTests.swift
Support Xcode 15.3 beta 1
- Support Swift 5.10 & Xcode 15.3
- Modify test matrix to 5.8, 5.9, 5.10
> Support Xcode 15.3 and Swift 5.10

- Sources/ScipioKit/Runner.swift
`extraBuildParametes` are not passed for the buildSettingsMatrix.
So we couldn't override `extraBuildParameters`....
> Add the missing argument

- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Producer/PIF/BuildParametersGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
Fix the issue that `buildOptionsMatrix` sometimes doesn't work for the specific target.
Scipio generates `PIF` for each package. Each target in the package uses the same PIF. However, `PIFGenerator` doesn't refer to the matrix, so target settings were applied for all targets in the same package.
This PR fixes this issue to refer to the matrix in generating the PIF phase.
> Pass buildOptionsMatrix to each target

- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
Link all dependencies to the target automatically. This setting is required when the dependencies are built as dynamic frameworks.
In the original PIFBuilder of SwiftPM, PackageProducts have link frameworks to their dependencies. However, Scipio ignores this and use library target to make framework instead.
So we need to add dependencies to the framework link phase of the library targets.
> Link all dependencies of targets

- Sources/ScipioKit/BuildOptions.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/scipio/CommandType.swift
- Sources/scipio/Options.swift
- Sources/scipio/scipio.docc/mergeable-library.md
- Sources/scipio/scipio.docc/prepare-cache-for-applications.md
- Sources/scipio/scipio.docc/scipio.md
- Tests/ScipioKitTests/RunnerTests.swift
Introduce a new framework type, `mergeable,` to build a Mergeable Library.
`--static` flag is deprecated. Use `--framework-type static` instead.
> Introduce Mergeable Library Support

- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
[Link all dependencies of targets by giginet · Pull Request #124 · giginet/Scipio](https://github.com/giginet/Scipio/pull/124)
#124 fixed the issue for some dynamic libraries
However, we found this change causes symbol duplications for some static frameworks.
It's better to revert this at this time. We have to introduce test cases for these situations next time.
> Revert #124

- Sources/scipio/CreateCommands.swift
- Sources/scipio/PrepareCommands.swift
`scipio` command doesn't show info log when `verbose`  is not specified from https://github.com/giginet/Scipio/commit/9fb11bf27ae650576edccafb6696012ba096af09 .
I asked @giginet about the issue in person, and he said it's a bug.
In this PR, I fixed the log level.
> Fix log level

- Sources/ScipioKit/DescriptionPackage.swift
- Tests/ScipioKitTests/DescriptionPackageTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/TestingPackage/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/TestingPackage/Sources/InternalExecutableTarget/InternalExecutableTarget.swift
- Tests/ScipioKitTests/Resources/Fixtures/TestingPackage/Sources/InternalRegularTarget/InternalRegularTarget.swift
- Tests/ScipioKitTests/Resources/Fixtures/TestingPackage/Tests/TestingPackageTests/TestingPackageTests.swift
The `DescriptionPackage` in `createPackage` mode may currently export internal targets that are not intended to be exported via `products`. This occurs because [PackageBuilder](https://github.com/swiftlang/swift-package-manager/blob/338edfdec96ce8fa8b9f33e12838f74a45063afc/Sources/PackageLoading/PackageBuilder.swift#L275) implicitly generates additional products in `ResolvedPackage.products` for executable and test targets (in addition to the actually exported products). These generated products may depend on internal targets that must not be built by `Scipio`.
Unlike `ResolvedPackage`, the [Manifest](https://github.com/swiftlang/swift-package-manager/blob/338edfdec96ce8fa8b9f33e12838f74a45063afc/Sources/PackageModel/Manifest/Manifest.swift#L80-L81) object accurately reflects all the …
> Fix DescriptionPackage resolves targets not exported via products

- Sources/ScipioKit/DescriptionPackage.swift
Fix CI for Xcode 16.
The test on the current main is broken with Xcode 16.
https://github.com/giginet/Scipio/actions/runs/9854164954/job/27206328940
```
2024-07-09T09:11:47.0455430Z /Users/runner/work/Scipio/Scipio/Tests/ScipioKitTests/DescriptionPackageTests.swift:76: error: -[ScipioKitTests.DescriptionPackageTests testBuildProductsInCreateMode] : XCTAssertEqual failed: ("["Logging", "MyTarget", "Logging", "MyTarget", "ExecutableTarget", "MyPlugin"]") is not equal to ("["Logging", "MyTarget", "ExecutableTarget", "MyPlugin"]") - Order of the resolved products should be correct
```
According to the build log, `resolveBuildProducts` returns duplicated `BuildProduct`.
It's better to use `OrderedSet` here to remove duplications and keep the order.
Strangely, this has not been produced with …
> Use OrderedSet for resolving products

- Sources/ScipioKit/DescriptionPackage.swift
In my personal application, the package contains a large number of targets, which causes the `resolveBuildProducts()` function to take a significant amount of time to execute. The common libraries added as dependencies to multiple targets lead to redundant generation of the same BuildProducts, resulting in overhead.
To address this issue, I created a `BuildProductsResolver` class. This class caches the targets passed to the `buildProducts(from:)` function in a visitedTargets property. By doing this, when the same target is encountered again, it returns early, preventing redundant processing. This change significantly reduces execution time by eliminating repeated operations.
> Improve `DescriptionPackage.resolveBuildProducts()` performance

- Sources/scipio/Arguments.swift
- Sources/scipio/CreateCommands.swift
- Sources/scipio/Options.swift
I have fixed an error that occurs when building with Xcode 16 Release Candidate.
This change is also included in #140, but I wanted to use it immediately, so I created a small separate PR.
* Removed unnecessary `@retroactive` declarations
> Fix build errors in Xcode16-RC

- .swiftlint.yml
In #142, I found there were codes violating `optional_data_string_conversion`.
In this PR, I addressed the warnings.
> Suppress swiftlint warnings

- .github/workflows/release.yml
I noticed that we can add x86_64 binary to an artifact bundle by build the project twice.
When scipio is built for arm64, the binary is generated at `./.build/arm64-apple-macosx/release/scipio`.
And when it is built for x86_64, the binary is generated at `./.build/x86_64-apple-macosx/release/scipio`.
[ArtifactBundleGen](https://github.com/freddi-kit/ArtifactBundleGen) used by scipio can combines both binaries into an artifact bundle when they exist.
This is the artifact bundle that I made in my forked repository.
https://github.com/mtj0928/Scipio/releases/download/0.21.0/scipio.artifactbundle.zip
> Add x86_64 binary to an artifact bundle in a release

- Package.swift
`swiftLanguageVersions` are obsoleted since Swift 6
> Use swiftLanguageMode instead

- .github/workflows/docc.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
To address node runtime deprecations:
- https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
- https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> Update actions/checkout to v4

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/PackageLocator.swift
- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/PIF/FrameworkComponentsCollector.swift
- Sources/ScipioKit/Producer/PIF/ModuleMapGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
This would make it easy for testing FrameworkComponentsCollector and FrameworkModuleMapGenerator.
> Factor out DescriptionPackage's path-related functions to PackageLocator protocol

- Sources/ScipioKit/Producer/FrameworkProducer.swift
That is not the actual restoration process, so should be done outside Restorer.
---
This is a preparation for #156.
> Factor out the validation logic of existing frameworks in the output directory from Restorer

- .spi.yml
- README.md
I did take the liberty to [add Scipio](https://github.com/SwiftPackageIndex/PackageList/issues/8446#event-15279386179) to [Swift Package Index](https://swiftpackageindex.com).
In order to have them host your documentation too we need to add this file that will allow their ci to build your documentation.
This PR contain the SwiftPackageIndex badges on the README.md file too.
> Add a file that will help Swift Package Index to host the documentation of Scipio

- .github/workflows/docc.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/Cache/LocalDiskCacheStorage.swift
- Sources/ScipioKit/Producer/Cache/ProjectCacheStorage.swift
- Sources/ScipioKit/Producer/CacheStorage+DisplayName.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Runner.swift
- Sources/scipio/CommandType.swift
- Sources/scipio/PrepareCommands.swift
- Sources/scipio/scipio.docc/build-pipeline.md
- Sources/scipio/scipio.docc/using-s3-storage.md
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/IntegrationTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
Resolves #148.
- `Runner.Options.CacheMode` is replaced with `[Runner.Options.CachePolicy]`
- `cacheMode: .disabled` -> `cachePolicies: []`
- `cacheMode: .project` -> `cachePolicies: [.project]`
- `cacheMode: .storage(storage, actors)` -> `cachePolicies: [.init(storage: storage, actors: actors)]`
- When saving, cache frameworks into all storages with `CacheActorKind.producer`
- When restoring, storages with `CacheActorKind.consumer` are used in order
- If first storage failed to restore some caches, the failed ones are tried to be fetched from second (next) storage
> Add multiple cache storages feature

- .github/workflows/tests.yml
- Tests/ScipioKitTests/CacheSystemTests.swift
ref: #146
- Avoid creating temp_TestingPackage in Tests/ScipioKitTests/Resources/Fixtures
- ~Convert to swift-testing~
- This made the CI unstable so reverted
> Refactor CacheSystemTests

- Sources/ScipioKit/PackageLocator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
ref:
- #166
- https://github.com/swiftlang/swift-package-manager/blob/bc689418acad746af6f2e24e6bef640e411d9bd7/Sources/Basics/FileSystem/RelativePath.swift#L15-L16
> Use TSCRelativePath typealias included in Basics and reduce TSCBasic imports

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Producer/BinaryExtractor.swift
- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/Cache/LocalDiskCacheStorage.swift
- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/DebugSymbol.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Producer/InfoPlistGenerator.swift
- Sources/ScipioKit/Producer/PIF/BuildParametersGenerator.swift
- Sources/ScipioKit/Producer/PIF/FrameworkBundleAssembler.swift
- Sources/ScipioKit/Producer/PIF/FrameworkModuleMapGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/ToolchainGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Sources/ScipioKit/Producer/PIF/XCBuildExecutor.swift
- Sources/ScipioKit/Runner.swift
- Sources/ScipioKit/URL+Extensions.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/DescriptionPackageTests.swift
- Tests/ScipioKitTests/FrameworkBundleAssemblerTests.swift
- Tests/ScipioKitTests/FrameworkModuleMapGeneratorTests.swift
- Tests/ScipioKitTests/InfoPlistGeneratorTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
- Use `TSCAbsolutePath` typealias
- Use `Basics.localFileSystem` which is an alias to `TSCBasic.localFileSystem`
- Make `DescriptionPackage.init` async and remove `tsc_await` usage
refs:
- #166
- #167
> Reduce TSCBasic usages

- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/DwarfExtractor.swift
This simplifies `Compiler.extractDebugSymbolPaths` implementation (by removing an unnecessary type).
> [Refactor] Move dwarfPath construction to DwarfExtractor and remove DebugSymbol type

- .github/workflows/release.yml
I'm not sure why but the release workflow for [0.27.0](https://github.com/giginet/Scipio/releases/tag/0.27.0) didn't ran. I added workflow_dispatch trigger for the workflow and would like to trigger that manually.
> Make release workflow enable to trigger manually

- Sources/ScipioKit/Runner.swift
🙈 
This pull request includes an update to the `Runner` struct in the `Sources/ScipioKit/Runner.swift` file to enhance configurability by using options from the `options` object.
* [`Sources/ScipioKit/Runner.swift`](diffhunk://#diff-ef410ed219f018d3487b31ad581e0a4ef813141371e708ca3c5c95c5a97f2657L76-R76): Modified the `onlyUseVersionsFromResolvedFile` parameter to use `options.shouldOnlyUseVersionsFromResolvedFile` for better configurability.
> Pass flags shouldOnlyUseVersionsFromResolvedFile

- Sources/ScipioKit/Producer/Cache/CacheSystem.swift
- Sources/ScipioKit/Producer/DwarfExtractor.swift
- Tests/ScipioKitTests/DebugSymbolTests.swift
Hello, giginet san and collaborators.
This PR will replace `NSRegularExpression` with modern regex, `Swift.Regex`.
I found two `TODO` comments, so I updated these methods:
- `parseClangVersion(from:)`: `xcrun clang --version` parser
- `parseUUIDs(from:)`: `xcrun dwarfdump --uuid <app>` parser
This PR will
- apply swift-testing to `DwarfExtractorTests` 
- add a test case to `.testExtractDwarfDump()`
Background:
`parseUUIDs(from:)` seems to be able to parse output containing more than one UUID.
I found such an output in https://developer.apple.com/library/archive/technotes/tn2339/_index.html.
```sh
$ xcrun dwarfdump --uuid  MySample.app/MySample
--
UUID: AD019F0E-1318-3F9F-92B6-9F95FBEBBE6F (armv7) MySample.app/MySample
UUID: BB59C973-06AC-388F-8EC1-FA3701C9E264 (arm64) …
```
> Use Swift.Regex to parse

- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Tests/ScipioKitTests/DebugSymbolTests.swift
- Tests/ScipioKitTests/FrameworkBundleAssemblerTests.swift
- Tests/ScipioKitTests/FrameworkModuleMapGeneratorTests.swift
- Tests/ScipioKitTests/PartialCacheTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/PartialCacheTestPackage/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/PartialCacheTestPackage/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/PartialCacheTestPackage/Sources/Bad/Bad.swift
- Tests/ScipioKitTests/Resources/Fixtures/PartialCacheTestPackage/Sources/Base/Base.swift
Closes #153 
This PR will fix the issue reported by #153.
`processAllTargets(buildProducts:)` will cache XCFrameworks that are successfully built.
Scipio users won't have to rebuild all frameworks even if Scipio fails to build some frameworks.
`PartialCacheTests` checks that `processAllTargets(buildProducts:)` works well.
Tests/ScipioKitTests/Resources/Fixtures/PartialCacheTestPackage provides two libraries, `Base` and `Bad.`
`Bad` depends on `Base` and cannot be compiled.
> Leave cache of frameworks that are successfully built

- Package.swift
- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
The branch can be built by Swift 6.0 compiler and works as expected (All tests are passed).
> Support swift-package-manager `release/6.1` branch

- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Tests/ScipioKitTests/RunnerTests.swift
In this PR, I fixed the issue causing valid local cache to be discarded and remote cache to be fetched.
The problem was that version files were created only for built targets, not for all targets. Previously, for caches obtained from local or remote sources, we did not generate version files. As a result, Scipio mistakenly marked valid local cache as invalid and fetched the remote cache unnecessarily.
> Fix issue causing valid local cache to be discarded and external cache to be fetched

- Package.swift
- Sources/ScipioKit/DescriptionPackage.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
We used to get the manifest information directly via SPM.
Now, I’ve migrated to parsing the JSON output from the `swift package dump-package` command using `PackageManifestKit`.
> Replace package manifest parsing with PackageManifestKit

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/Resolver/ModuleTypeResolver.swift
- Sources/ScipioKit/Resolver/ResolvedModels.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithExplicitPath/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithExplicitPath/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithExplicitPath/path/WithExplicitPath/WithExplicitPath.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_source/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_source/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_source/source/WithoutPath_LowercaseDir_source/WithoutPath_LowercaseDir_source.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_sources/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_sources/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_sources/sources/WithoutPath_LowercaseDir_sources/WithoutPath_LowercaseDir_sources.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_src/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_src/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_src/src/WithoutPath_LowercaseDir_src/WithoutPath_LowercaseDir_src.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_srcs/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_srcs/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_LowercaseDir_srcs/src/WithoutPath_LowercaseDir_srcs/WithoutPath_LowercaseDir_srcs.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_SingleModule/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_SingleModule/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_SingleModule/Source/WithoutPath_SingleModule.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_UppercaseMix/.gitignore
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_UppercaseMix/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/VariousModulePathsTests/WithoutPath_UppercaseMix/sOuRcEs/WithoutPath_UppercaseMix/WithoutPath_UppercaseMix.swift
- Tests/ScipioKitTests/VariousModulePathsTests.swift
Previously, `ModuleTypeResolver` could only resolve modules located under the following directory structures:
* `Sources/<target name>`
* `src/<target name>`
However, SwiftPM treats these directory names in a case-insensitive manner. This means that modules placed under directories like `sources/` or `SRC/`, which are valid in SwiftPM, were not recognized by `ModuleTypeResolver`.
Additionally, in packages that contain only a single module, SwiftPM allows placing source files directly under `Sources/` (e.g. `Sources/main.swift`) without a subdirectory. The previous implementation did not account for this layout either.
This PR updates `resolveTargetFullPath` to handle:
* Case-insensitive matching of standard source directories (`sources`, `source`, `src`, `srcs`)
* Single-module packages …
> Improve `ModuleTypeResolver.resolveTargetFullPath` to support case-insensitive matching of default module directories

- Tests/ScipioKitTests/DescriptionPackageTests.swift
- Tests/ScipioKitTests/IntegrationTests.swift
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationMacTestPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationMacTestPackage/Package.swift
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationTestPackage/Package.resolved
- Tests/ScipioKitTests/Resources/Fixtures/IntegrationTestPackage/Package.swift
This PR updates the test fixtures used in ScipioKit’s integration tests to use the latest versions of swift-nio and swift-nio-ssl.
Originally, the fixtures specified swift-nio with from: 2.0.0, but when version 2.83.0 was used locally, some tests failed due to API changes.
To fix this, the fixtures are now updated to 2.83.0, and the test code has been modified to match the updated APIs.
> Bump `swift-nio` & `swift-nio-ssl` in integration test fixtures and update tests

- Sources/ScipioKit/DescriptionPackage.swift
- Sources/ScipioKit/PackageLocator.swift
- Sources/ScipioKit/Producer/BinaryExtractor.swift
- Sources/ScipioKit/Producer/Compiler.swift
- Sources/ScipioKit/Producer/DwarfExtractor.swift
- Sources/ScipioKit/Producer/FrameworkProducer.swift
- Sources/ScipioKit/Producer/InfoPlistGenerator.swift
- Sources/ScipioKit/Producer/PIF/BuildParametersGenerator.swift
- Sources/ScipioKit/Producer/PIF/FrameworkBundleAssembler.swift
- Sources/ScipioKit/Producer/PIF/FrameworkComponentsCollector.swift
- Sources/ScipioKit/Producer/PIF/FrameworkModuleMapGenerator.swift
- Sources/ScipioKit/Producer/PIF/PIFCompiler.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/ToolchainGenerator.swift
- Sources/ScipioKit/Producer/PIF/XCBuildClient.swift
- Sources/ScipioKit/Producer/PIF/XCBuildExecutor.swift
- Sources/ScipioKit/Runner.swift
- Sources/ScipioKit/URL+Extensions.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/DebugSymbolTests.swift
- Tests/ScipioKitTests/DescriptionPackageTests.swift
- Tests/ScipioKitTests/FrameworkBundleAssemblerTests.swift
- Tests/ScipioKitTests/FrameworkModuleMapGeneratorTests.swift
- Tests/ScipioKitTests/InfoPlistGeneratorTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
- Tests/ScipioKitTests/URLExtensionsTests.swift
I migrated `AbsolutePath` and `RelativePath` to `Foundation.URL`.
> Migrate AbsolutePath and RelativePath to URL

- Sources/ScipioKit/Executor.swift
- Tests/ScipioKitTests/CacheSystemTests.swift
- Tests/ScipioKitTests/DWARFSymbolStripperTests.swift
- Tests/ScipioKitTests/PartialCacheTests.swift
- Tests/ScipioKitTests/ProcessExecutorTests.swift
- Tests/ScipioKitTests/RunnerTests.swift
- Tests/ScipioKitTests/TestingExecutor.swift
- Tests/ScipioKitTests/VariousModulePathsTests.swift
- Tests/ScipioKitTests/XCTestCase+Utils.swift
- Tests/ScipioKitTests/XcodeVersionFetcherTests.swift
This PR makes the existing `ProcessExecutor` in ScipioKit publicly accessible under `@_spi(Internals)`.
Custom build pipelines in ScipioKit sometimes require executing shell commands.  
However, `TSC.Process` is not `Sendable` and cannot be abstracted via protocols.
To address these limitations, `ProcessExecutor` was previously introduced as a `Sendable` and protocol-oriented alternative.
By exposing it through `@_spi(Internals)`, this PR enables executing arbitrary commands in a `Sendable` and testable way, simplifying the development of custom pipelines in ScipioKit.
> Expose ProcessExecutor via `@_spi(Internals)`

- Package.swift
- Sources/ScipioKit/Producer/PIF/PIFGenerator.swift
- Sources/ScipioKit/Producer/PIF/ToolchainGenerator.swift
- Sources/ScipioKit/SwiftPM/StringConversions.swift
- Sources/ScipioKit/SwiftPM/StringMangling.swift
I migrated utility functions (e.g. `spm_shellEscaped()`) from swift-tools-support-core and removed it as a dependency.
> Migrate utility functions from swift-tools-support-core and removed it as a dependency

- Sources/ScipioKit/Executor.swift
- Tests/ScipioKitTests/TestingExecutor.swift
I added an environment parameter to ProcessExecutor to support executing processes with custom environment variables.
This change enables use of ScipioKit in custom build pipelines that require specific environment configurations.
> Update ProcessExecutor to support environment variables

- Sources/ScipioKit/Executor.swift
Fix a rare “bad file descriptor” error by explicitly closing FileHandle.
In rare cases, ClangChecker fails with a “bad file descriptor” error when executing commands via ProcessExecutor:
https://github.com/giginet/Scipio/blob/28383cec93e01815c7666997c957b6b8efa989cc/Sources/ScipioKit/Producer/Cache/CacheSystem.swift#L25
According to Apple’s documentation, FileHandle usually doesn’t need to be closed manually:
> You don’t need to send closeFile() to this object or explicitly release the object after you have finished using it.
https://developer.apple.com/documentation/foundation/pipe/filehandleforreading
However, this behavior has been reported in the following Swift issue, where a "bad file descriptor" error can occur under specific conditions such as high concurrency or quick process …
> Close FileHandle explicitly to prevent `bad file descriptor` error

- Sources/ScipioKit/Executor.swift
- Tests/ScipioKitTests/ClangCheckerTests.swift
- Tests/ScipioKitTests/DebugSymbolTests.swift
- Tests/ScipioKitTests/TestingExecutor.swift
This PR makes the `Executor` protocol conform to Sendable.
> Make Executor conform to Sendable

- Package.swift
```
warning: 'scipio': found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/runner/work/Scipio/Scipio/Tests/PIFKitTests/Fixtures/BuildConfiguration.json
/Users/runner/work/Scipio/Scipio/Tests/PIFKitTests/Fixtures/SimplePackage.pif
/Users/runner/work/Scipio/Scipio/Tests/PIFKitTests/Fixtures/Target.json
warning: 'scipio': found 2 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/runner/work/Scipio/Scipio/Sources/ScipioKit/SwiftPM/NOTICE.txt
/Users/runner/work/Scipio/Scipio/Sources/ScipioKit/SwiftPM/LICENSE
```
> Resolve some unhandled files warnings in SwiftPM
